workflows:
  unity-ios-build:
    name: Unity iOS Build

    environment:
      xcode: latest

    scripts:

      - name: Install Unity
        script: |
          brew install --cask unity-hub
          unityhub -- --headless install \
          --version 2023.2.18f1 \
          --module ios

      - name: Build iOS
        script: |
          /Applications/Unity/Hub/Editor/2023.2.18f1/Unity.app/Contents/MacOS/Unity \
          -batchmode \
          -quit \
          -projectPath . \
          -executeMethod BuildScript.BuildIOS

    artifacts:
      - build/ios/*.ipa